---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: README.md
  label: README
  match: "**/*"
  read_only: true
- type: heading
  label: Blog Post
- type: directory
  path: content/post
  label: Post
  create: all
  match: "**/*"
- type: heading
  label: Others Pages
- type: directory
  path: content/docs
  label: Docs
  create: all
  match: "**/*"
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/services
  label: Services
  create: all
  match: "**/*"
- type: directory
  path: content/products
  label: Products
  create: all
  match: "**/*"
- type: directory
  path: content
  label: All Pages
  create: all
  match: "**/*"
- type: heading
  label: Configuration
- type: document
  path: config.toml
  label: Configuration
  match: "**/*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.81.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.81.0
